services:
  postgres:
    image: postgres:16-alpine
    container_name: restaurant-postgres
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d restaurantdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: restaurant-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurantdb
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: "123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_SQL_INIT_MODE: never
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
